### ISSUE TITLE
不支持翻译多行文本

### ISSUE THREAD

**Issue by kense-lab** [sainnhe/tmux-translator#1]

**Comment by sainnhe** [comment]
应该修好了

**Comment by kense-lab** [comment]
如果翻译句子中间有换行的话, 翻译就不对了, 被截断了

**Comment by sainnhe** [comment]
这个插件只是 [skywind3000/translator](https://github.com/skywind3000/translator) 的一个 wrapper，韦大的脚本就是这么设计的。

你要是觉得有问题的话建议去他的仓库反馈，或者直接 fork。

**Comment by kense-lab** [comment]
好的，thank you
