### ISSUE TITLE
窗口直接闪退

### ISSUE THREAD

**Issue by improve100** [sainnhe/tmux-translator#4]
ubuntu1604 tmux 3.3a
测试命令行OK：
python /home/xxx/.tmux/plugins/tmux-translator/engine/translator.py --engine=google engine
engine
引擎
[v] 发动机;
[n] 发动机;引擎;机;机车;
 * 发动机
测试tmux会闪退：
tmux popup -w 50 -h 20 -E "python /home/xxx/.tmux/plugins/tmux-translator/engine/translator.py --engine=google hello"

**Comment by sainnhe** [comment]
这行命令能运行成功吗？

```bash
tmux popup -w 50 -h 20 -E "echo foo; read -r"
```

**Comment by improve100** [comment]
done <<< "$vars"
result="${result}"
tmux popup -w $(get_width) -h $(get_height) "$result"
改成这个就好了。

**Comment by sainnhe** [comment]
这样没有办法回车退出，只能 Ctrl-C 退出。`-E` 是有必要的。

这个 Bug 在 macOS 和 Arch Linux 上都无法复现，应该是 Ubuntu 打包的问题导致 tmux 无法使用 `-E` 选项，建议反馈给 Ubuntu 上游。
